use axum::{
    extract::{Path, State},
    http::{header, StatusCode},
    response::IntoResponse,
    routing::get,
    Router,
};
use rmb_core::IndexReader;
use memmap2::Mmap;
use std::{fs::File, sync::Arc};
use tokio::net::TcpListener;

// --- 1. SHARED GLOBAL STATE ---

/// This structure lives in RAM and is shared between all requests (threads)
/// arriving at the server simultaneously.
struct AppState {
    // Our binary search engine (O(log N) search)
    index: IndexReader,
    // The full text file mapped directly into RAM
    jsonl_mmap: Mmap,
}

// --- 2. ENTRY POINT (MAIN) ---

#[tokio::main]
async fn main() {
    println!("Starting RMB emergency engine...");

    // 1. Load the binary index using our `core` library
    let index = IndexReader::new("main.idx")
        .expect("CRITICAL: Could not load main.idx");

    // 2. Map the perfect JSONL into RAM using the OS
    let jsonl_file = File::open("perfect.jsonl")
        .expect("CRITICAL: perfect.jsonl not found");
    
    // We commit that nobody will modify the JSONL while the server is running
    let jsonl_mmap = unsafe { 
        memmap2::MmapOptions::new().map(&jsonl_file)
            .expect("CRITICAL: JSONL mmap failed") 
    };

    // 3. Wrap state in Arc (atomic reference count)
    // This allows multiple web server threads to read the same memory region
    // simultaneously without cloning gigabytes of data.
    let shared_state = Arc::new(AppState { index, jsonl_mmap });

    // 4. Set up the API router
    let app = Router::new()
        // When someone visits /records/23737, run the `get_record` handler
        .route("/records/{id}", get(get_record))
        // Inject shared state into all routes
        .with_state(shared_state);

    // 5. Run the server on port 3000
    let listener = TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("RMB Fallback server is ACTIVE at http://localhost:3000");
    
    axum::serve(listener, app).await.unwrap();
}

// --- 3. ENDPOINT (O(1) MAGIC) ---

/// Controller for `GET /records/:id`
async fn get_record(
    // Extract ID from URL
    Path(id): Path<u32>,
    // Extract global state (mmaps) from memory
    State(state): State<Arc<AppState>>,
) -> impl IntoResponse {
    
    // STEP 1: Microsecond Binary Search in .idx
    if let Some(record) = state.index.find_by_id(id) {
        
        // STEP 2: Pointer math
        // We know exactly where the record starts and ends in RAM
        let start = record.offset as usize;
        let end = start + record.length as usize;

        // STEP 3: Byte slicing
        // Extract only that slice from gigabytes of memory.
        // NOTE: We are not parsing JSON. These are raw bytes.
        let chunk = &state.jsonl_mmap[start..end];

        // STEP 4: Return bytes directly to the network stack,
        // wrapped as JSON so the client can read it.
        (
            StatusCode::OK,
            [(header::CONTENT_TYPE, "application/json")],
            chunk.to_vec(), // Copy the slice to the HTTP output buffer
        )

    } else {
        // If the ID does not exist in the binary index
        (
            StatusCode::NOT_FOUND,
            [(header::CONTENT_TYPE, "application/json")],
            r#"{"error": "Record not found in backup index"}"#.as_bytes().to_vec(),
        )
    }
}

// --- 4. API INTEGRATION TESTS ---

#[cfg(test)]
mod tests {
    use super::*; // Import everything above (AppState, get_record, etc.)
    use axum::{
        body::Body,
        http::{Request, StatusCode},
    };
    use tower::ServiceExt; // Gives us the ability to call app.oneshot(request)

    #[tokio::test]
    async fn test_api_existing_and_non_existing_record() {
        println!("Setting up in-memory test environment...");

        // 1. Load the real files generated by the indexer (one level up with ../)
        let index = IndexReader::new("../main.idx")
            .expect("The test requires main.idx to exist at project root");
        
        let jsonl_file = File::open("../perfect.jsonl")
            .expect("The test requires perfect.jsonl to exist at project root");
        
        let jsonl_mmap = unsafe { 
            memmap2::MmapOptions::new().map(&jsonl_file).unwrap() 
        };

        let shared_state = Arc::new(AppState { index, jsonl_mmap });

        // 2. Rebuild exactly the same router as production
        let app = Router::new()
            .route("/records/{id}", get(get_record))
            .with_state(shared_state);

        // --- CASE A: EXISTING RECORD (ID 23737) ---
        // 3. Create a manual HTTP request
        let request_ok = Request::builder()
            .uri("/records/23737")
            .body(Body::empty())
            .unwrap();

        // 4. Send the request to the router without using the network
        // .clone() is required because oneshot consumes the router
        let response_ok = app.clone().oneshot(request_ok).await.unwrap();

        // 5. Verify the server returned 200 OK
        assert_eq!(response_ok.status(), StatusCode::OK);

        // --- CASE B: NON-EXISTENT RECORD (ID 99999) ---
        let request_not_found = Request::builder()
            .uri("/records/99999")
            .body(Body::empty())
            .unwrap();

        let response_not_found = app.oneshot(request_not_found).await.unwrap();

        // Verify the server returned 404 Not Found
        assert_eq!(response_not_found.status(), StatusCode::NOT_FOUND);
        
        println!("API endpoints respond correctly without using network ports!");
    }
}